### ISSUE TITLE
Распределение игрушек внутри треугольника

### ISSUE THREAD

**Issue by elaman** [darina-m/christmas-tree#3]
1. Использовать Math.random чтобы создать координаты точки
2. Проверить находится ли точка внутри треугольника (елки) используя геометрические функции - если нет, то выполнить шаг 1. Если да, то вывести ее.

Можно использовать код pizza-builder как пример

**Comment by elaman** [comment]
Не вижу прогресса здесь

**Comment by darina-m** [comment]
извините агай ,  я пыталась сделать сама ,но у меня не получается
